In [1]:
import pandas as pd


%load_ext autoreload
%autoreload 2
import utils

import warnings
warnings.filterwarnings("ignore")

In [2]:
df_reviews = pd.read_csv('data/user_review_limpio.csv', encoding='utf-8')
df_games = pd.read_csv('data/steam_games_limpio.csv', encoding='utf-8')
df_items = pd.read_csv('data/user_items_limpio.csv', encoding='utf-8')

In [23]:
df_reviews

,user_id,user_url,reviews_item_id,reviews_helpful,reviews_recommend,reviews_date,sentiment_analysis
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,1250,No ratings yet,True,2011-11-05,1
1,js41637,http://steamcommunity.com/id/js41637,251610,15 of 20 people (75%) found this review helpful,True,2014-06-24,1
2,evcentric,http://steamcommunity.com/id/evcentric,248820,No ratings yet,True,Formato inválido,2
3,doctr,http://steamcommunity.com/id/doctr,250320,2 of 2 people (100%) found this review helpful,True,2013-10-14,2
4,maplemage,http://steamcommunity.com/id/maplemage,211420,35 of 43 people (81%) found this review helpful,True,2014-04-15,1
...,...,...,...,...,...,...,...
57392,How51,http://steamcommunity.com/id/How51,440,No ratings yet,True,2014-08-15,1
57393,76561198111410893,http://steamcommunity.com/profiles/76561198111...,304930,No ratings yet,True,2014-08-02,1
57394,zaza147,http://steamcommunity.com/id/zaza147,265630,No ratings yet,True,2015-07-31,2
57395,lifeonhigh,http://steamcommunity.com/id/lifeonhigh,304050,No ratings yet,True,2015-12-20,1
57396,EchoXSilence,http://steamcommunity.com/id/EchoXSilence,570,0 of 2 people (0%) found this review helpful,False,Formato inválido,1

In [33]:
df_reviews[df_reviews['reviews_item_id']=='733530']

Empty DataFrame
Columns: [user_id, user_url, reviews_item_id, reviews_helpful, reviews_recommend, reviews_date, sentiment_analysis]
Index: []

In [48]:
df_games.head(20)

,genres,price,early_access,id,release_anio,publisher,app_name,title,developer
0,Action,4.99,False,761140,2018,Kotoshiro,Lost Summoner Kitty,Lost Summoner Kitty,Kotoshiro
1,Casual,4.99,False,761140,2018,Kotoshiro,Lost Summoner Kitty,Lost Summoner Kitty,Kotoshiro
2,Indie,4.99,False,761140,2018,Kotoshiro,Lost Summoner Kitty,Lost Summoner Kitty,Kotoshiro
3,Simulation,4.99,False,761140,2018,Kotoshiro,Lost Summoner Kitty,Lost Summoner Kitty,Kotoshiro
4,Strategy,4.99,False,761140,2018,Kotoshiro,Lost Summoner Kitty,Lost Summoner Kitty,Kotoshiro
5,Free to Play,0.00,False,643980,2018,"Making Fun, Inc.",Ironbound,Ironbound,Secret Level SRL
6,Indie,0.00,False,643980,2018,"Making Fun, Inc.",Ironbound,Ironbound,Secret Level SRL
7,RPG,0.00,False,643980,2018,"Making Fun, Inc.",Ironbound,Ironbound,Secret Level SRL
8,Strategy,0.00,False,643980,2018,"Making Fun, Inc.",Ironbound,Ironbound,Secret Level SRL
9,Casual,0.00,False,670290,2017,Poolians.com,Real Pool 3D - Poolians,Real Pool 3D - Poolians,Poolians.com
10,Free to Play,0.00,False,670290,2017,Poolians.com,Real Pool 3D - Poolians,Real Pool 3D - Poolians,Poolians.com
11,Indie,0.00,False,670290,2017,Poolians.com,Real Pool 3D - Poolians,Real Pool 3D - Poolians,Poolians.com
12,Simulation,0.00,False,670290,2017,Poolians.com,Real Pool 3D - Poolians,Real Pool 3D - Poolians,Poolians.com
13,Sports,0.00,False,670290,2017,Poolians.com,Real Pool 3D - Poolians,Real Pool 3D - Poolians,Poolians.com
14,Action,0.99,False,767400,2017,彼岸领域,弹炸人2222,弹炸人2222,彼岸领域
15,Adventure,0.99,False,767400,2017,彼岸领域,弹炸人2222,弹炸人2222,彼岸领域
16,Casual,0.99,False,767400,2017,彼岸领域,弹炸人2222,弹炸人2222,彼岸领域
17,Action,3.99,False,772540,2018,Trickjump Games Ltd,Battle Royale Trainer,Battle Royale Trainer,Trickjump Games Ltd
18,Adventure,3.99,False,772540,2018,Trickjump Games Ltd,Battle Royale Trainer,Battle Royale Trainer,Trickjump Games Ltd
19,Simulation,3.99,False,772540,2018,Trickjump Games Ltd,Battle Royale Trainer,Battle Royale Trainer,Trickjump Games Ltd

In [32]:
df_games[df_games['id']=='733530']

Empty DataFrame
Columns: [genres, price, early_access, id, release_anio, publisher, app_name, title, developer]
Index: []

In [47]:
df_items.head(20)

,item_id,item_name,playtime_forever,playtime_2weeks,steam_id,items_count,user_id
0,10,Counter-Strike,6,0,76561197970982479,277,76561197970982479
1,20,Team Fortress Classic,0,0,76561197970982479,277,76561197970982479
2,30,Day of Defeat,7,0,76561197970982479,277,76561197970982479
3,40,Deathmatch Classic,0,0,76561197970982479,277,76561197970982479
4,50,Half-Life: Opposing Force,0,0,76561197970982479,277,76561197970982479
5,60,Ricochet,0,0,76561197970982479,277,76561197970982479
6,70,Half-Life,0,0,76561197970982479,277,76561197970982479
7,130,Half-Life: Blue Shift,0,0,76561197970982479,277,76561197970982479
8,300,Day of Defeat: Source,4733,0,76561197970982479,277,76561197970982479
9,240,Counter-Strike: Source,1853,0,76561197970982479,277,76561197970982479
10,3830,Psychonauts,333,0,76561197970982479,277,76561197970982479
11,2630,Call of Duty 2,75,0,76561197970982479,277,76561197970982479
12,3900,Sid Meier's Civilization IV,338,0,76561197970982479,277,76561197970982479
13,34440,Sid Meier's Civilization IV,0,0,76561197970982479,277,76561197970982479
14,3920,Sid Meier's Pirates!,2,0,76561197970982479,277,76561197970982479
15,6400,Joint Task Force,286,0,76561197970982479,277,76561197970982479
16,6910,Deus Ex: Game of the Year Edition,2685,0,76561197970982479,277,76561197970982479
17,7670,BioShock,633,0,76561197970982479,277,76561197970982479
18,409710,BioShock Remastered,0,0,76561197970982479,277,76561197970982479
19,220,Half-Life 2,696,0,76561197970982479,277,76561197970982479

In [45]:
#/658870/EXIT_2__Directions/'
df_items[df_items['item_name']=='EXIT 2 - Directions']

Empty DataFrame
Columns: [item_id, item_name, playtime_forever, playtime_2weeks, steam_id, items_count, user_id]
Index: []